### ISSUE TITLE
How to enable GPU while doing inference using validate_yolo.py?

### ISSUE THREAD

**Issue by dsbyprateekg** [david8862/keras-YOLOv3-model-set#98]
Hi @david8862 ,

I am using tools/evaluation/validate_yolo.py file on test images but the inference time is longer.
For 10 images, Average Inference time is as below-
![time](https://user-images.githubusercontent.com/30830541/87867533-78b5ea80-c9ab-11ea-80cb-4427e360c802.JPG)

I suspect this script is not using GPU.

Can you please tell me where and what changes I can add to enable the GPU so that the inference time becomes smaller?

**Comment by david8862** [comment]
what's your model format? For .h5 and .pb it should be able to pick GPU if it's available.

**Comment by dsbyprateekg** [comment]
@david8862 it's in .h5 format
This behavior is strange.
When I run the inference in my local system, it uses CPU.
But in Kaggle notebook, I am seeing it's using GPU.

**Comment by dsbyprateekg** [comment]
I am able to solve this error. It was due to the model was loaded in each request.
P put the model loading code inside main and now it's working.
